version: '3'
  
services:
    test_redis:
        image: redis:6
        command: redis-server --appendonly yes
        restart: always
        container_name: test_redis
        expose:
            - 6379 
    web_testing:
        container_name: web_testing
        build:
            context: .
            dockerfile: Dockerfile 
        env_file: .env
        environment:
            - REDIS_URL=redis://test_redis
        restart: always 
        ports:
            - 8015:8113 
        expose:
            - 8015
        links:
            - test_redis 
        command: sh -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate && supervisord -n"
 