# Generated by Django 5.0.4 on 2024-04-27 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Сurrency",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=250)),
                ("code", models.CharField(max_length=250)),
                ("rq_code", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="ExcRates",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("date_status", models.DateField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.сurrency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
                "db_table": "exc_rates",
            },
        ),
    ]
